set(_CATKIN_CURRENT_PACKAGE "web_server")
set(web_server_VERSION "0.0.0")
set(web_server_MAINTAINER "shubham <shubham@todo.todo>")
set(web_server_PACKAGE_FORMAT "2")
set(web_server_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(web_server_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(web_server_BUILDTOOL_DEPENDS "catkin")
set(web_server_BUILDTOOL_EXPORT_DEPENDS )
set(web_server_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(web_server_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(web_server_TEST_DEPENDS )
set(web_server_DOC_DEPENDS )
set(web_server_URL_WEBSITE "")
set(web_server_URL_BUGTRACKER "")
set(web_server_URL_REPOSITORY "")
set(web_server_DEPRECATED "")