set(_CATKIN_CURRENT_PACKAGE "odom_setup")
set(odom_setup_VERSION "0.0.0")
set(odom_setup_MAINTAINER "nvidia <nvidia@todo.todo>")
set(odom_setup_PACKAGE_FORMAT "2")
set(odom_setup_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "tf" "nav_msgs")
set(odom_setup_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "tf" "nav_msgs")
set(odom_setup_BUILDTOOL_DEPENDS "catkin")
set(odom_setup_BUILDTOOL_EXPORT_DEPENDS )
set(odom_setup_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "tf" "nav_msgs")
set(odom_setup_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "tf" "nav_msgs")
set(odom_setup_TEST_DEPENDS )
set(odom_setup_DOC_DEPENDS )
set(odom_setup_URL_WEBSITE "")
set(odom_setup_URL_BUGTRACKER "")
set(odom_setup_URL_REPOSITORY "")
set(odom_setup_DEPRECATED "")